name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  echo-input:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/github-script@v6
        env:
          FIRST_NAME: Mona
          LAST_NAME: Octocat
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v2',
              sha: context.sha
            })
