name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  hello:
    run-name: this is run-name
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo hello
  deploy:
    needs: hello
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: manual approval
        echo: approved manually
