name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo hello
      - name: deps
        uses: hurricanenara/espresso@v2
