name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

env:
  AWS_ENV: something

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo hello
      - name: Evaluate aws environment
        run: |
          if [[ uat == dev ]]; then
            echo "its dev"
          else
            echo "its not dev"
          fi
      - name: Print env
        run: echo ${{ env.AWS_ENV }}
